export * from './IUbicacion';
export * from './iBiblioteca';
export * from './iCultura';
export * from './iHistoria';
export * from './iNews';
export * from './iPresidente';
export * from './iProducto';
export * from './iresponse';
export * from './iuser';
